name: noc-scraper-v2

on:
  workflow_dispatch:
  #schedule:
   # - cron: '0,15,30,45 7-16 * * 2-6'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4.1.1
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache dependency libraries
        uses: actions/cache@v4
        id: cache-libraries
        with:
          path: ${{ env.pythonLocation }}/lib/python3.10/site-packages
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install pip and dependencies
        if: steps.cache-libraries.outputs.cache-hit != 'true' 
        run: |
          python -m pip install -r requirements.txt

      - name: execute python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python noc_scraper.py

      #- name: check for changes
        #run: git status
      - name: git config
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: stage changed files
        run: git add .
      - name: check status
        run: git status
      - name: commit changed files
        run: git commit -m "Updating ignore_id.txt" || true #git diff --exit-code || 
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
        
